# Generated by Django 3.1.7 on 2021-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField(max_length=30)),
                ('number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
