# Generated by Django 3.1.7 on 2021-03-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_auto_20210317_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='uname',
            new_name='username',
        ),
    ]
