# Generated by Django 3.1.7 on 2021-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_auto_20210317_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_details',
            old_name='name',
            new_name='namee',
        ),
        migrations.RenameField(
            model_name='booking_details',
            old_name='username',
            new_name='usernamee',
        ),
    ]
