# Generated by Django 3.1.7 on 2021-03-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_auto_20210317_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='passwd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
