# Generated by Django 3.1.7 on 2021-03-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_customers_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='passwd',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='usernamed',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
