# Generated by Django 3.1.7 on 2021-03-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_auto_20210318_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='namee',
        ),
        migrations.RemoveField(
            model_name='booking_details',
            name='usernamee',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='usernamed',
        ),
        migrations.AddField(
            model_name='booking_details',
            name='name',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
