# Generated by Django 3.1.7 on 2021-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_auto_20210318_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
