# Generated by Django 3.1.7 on 2021-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_auto_20210318_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
