# Generated by Django 3.1.7 on 2021-03-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_auto_20210318_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='name',
        ),
    ]
