# Generated by Django 3.1.7 on 2021-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_auto_20210318_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
