# Generated by Django 3.1.7 on 2021-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0014_auto_20210318_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
