# Generated by Django 3.1.7 on 2021-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0015_auto_20210318_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customers',
            name='age',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dob',
            field=models.DateField(max_length=50),
        ),
    ]
