# Generated by Django 3.1.7 on 2021-03-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0016_auto_20210318_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
